# Virtual Dispacher Database Schema
# Last Edit: 10/19/2018 7:54 PM

DROP DATABASE IF EXISTS vd_db;
CREATE DATABASE vd_db;
USE vd_db;

CREATE TABLE pilot (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	f_name VARCHAR(30) NOT NULL,
	l_name VARCHAR(30) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE aircraft (
	id SMALLINT NOT NULL AUTO_INCREMENT,
	operational BOOLEAN NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE zones (
	id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (id)
);

CREATE TABLE avaliability (
	pilot_id SMALLINT UNSIGNED NOT NULL UNIQUE,
	created TIME NOT NULL,
	PRIMARY KEY (pilot_id)
);

CREATE TABLE flights (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	completed BOOLEAN NOT NULL,
	pilot_id SMALLINT UNSIGNED NOT NULL,
	aircraft_id SMALLINT NOT NULL,
	zone_id TINYINT UNSIGNED NOT NULL,
	PRIMARY KEY (id)
);

# ADD FOREIGN KEY CONSTRAINTS

ALTER TABLE avaliability
	ADD FOREIGN KEY (pilot_id)
	REFERENCES pilot (id)
	ON DELETE CASCADE;

ALTER TABLE flights
	ADD FOREIGN KEY (aircraft_id)
	REFERENCES aircraft (id)
	ON DELETE NO ACTION;